"""empty message

Revision ID: 473783e4bbae
Revises: 
Create Date: 2020-11-04 11:58:42.676145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473783e4bbae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_category_rate_by_une_and_period',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=128), nullable=False),
    sa.Column('une', sa.String(length=128), nullable=False),
    sa.Column('rate_category_moda', sa.Numeric(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('otb_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numberCurrentPeriodOTB', sa.Integer(), nullable=False),
    sa.Column('daysLongCurrentPeriodOTB', sa.Integer(), nullable=False),
    sa.Column('startDateCurrentPeriodOTB', sa.DateTime(), nullable=False),
    sa.Column('isFutureProjection', sa.Boolean(), nullable=False),
    sa.Column('daysLongProjectionPeriodOTB', sa.Integer(), nullable=False),
    sa.Column('startDateProjectionPeriodOTB', sa.DateTime(), nullable=True),
    sa.Column('une', sa.String(length=128), nullable=False),
    sa.Column('submarca', sa.String(length=128), nullable=False),
    sa.Column('categoria', sa.String(length=128), nullable=False),
    sa.Column('mercado', sa.String(length=128), nullable=False),
    sa.Column('initialStock', sa.Numeric(), nullable=False),
    sa.Column('inventoryOnStores', sa.Numeric(), nullable=False),
    sa.Column('purchases', sa.Numeric(), nullable=False),
    sa.Column('devolution', sa.Numeric(), nullable=False),
    sa.Column('targetSells', sa.Numeric(), nullable=False),
    sa.Column('targetStock', sa.Numeric(), nullable=False),
    sa.Column('projectionEomStock', sa.Numeric(), nullable=False),
    sa.Column('otb_minus_ctb', sa.Numeric(), nullable=False),
    sa.Column('percentage_otb', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relation_client_mercado',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client', sa.String(length=128), nullable=False),
    sa.Column('isM1', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_client_mercado')
    op.drop_table('otb_results')
    op.drop_table('control_category_rate_by_une_and_period')
    # ### end Alembic commands ###
